// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice = EmbeddedVideoSlice | QuoteSlice | RichTextBlockSlice | FeaturedImageSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
    /**
     * featured field in *Blog Post*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: blog_post.featured
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    featured: prismic.BooleanField;

    /**
     * Title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: {{Blog Title Here}}
     * - **API ID Path**: blog_post.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Publication Date field in *Blog Post*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.publication_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    publication_date: prismic.DateField;

    /**
     * Slice Zone field in *Blog Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
     * Meta Title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: blog_post.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: blog_post.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;

export type AllDocumentTypes = BlogPostDocument;

/**
 * Primary content in *EmbeddedVideo → Default → Primary*
 */
export interface EmbeddedVideoSliceDefaultPrimary {
    /**
     * Embedded Video field in *EmbeddedVideo → Default → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: embedded_video.default.primary.embedded_video
     * - **Documentation**: https://prismic.io/docs/field#embed
     */
    embedded_video: prismic.EmbedField;
}

/**
 * Default variation for EmbeddedVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbeddedVideoSliceDefault = prismic.SharedSliceVariation<"default", Simplify<EmbeddedVideoSliceDefaultPrimary>, never>;

/**
 * Slice variation for *EmbeddedVideo*
 */
type EmbeddedVideoSliceVariation = EmbeddedVideoSliceDefault;

/**
 * EmbeddedVideo Shared Slice
 *
 * - **API ID**: `embedded_video`
 * - **Description**: EmbeddedVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbeddedVideoSlice = prismic.SharedSlice<"embedded_video", EmbeddedVideoSliceVariation>;

/**
 * Primary content in *FeaturedImage → Default → Primary*
 */
export interface FeaturedImageSliceDefaultPrimary {
    /**
     * Featured Image field in *FeaturedImage → Default → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: featured_image.default.primary.featured_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    featured_image: prismic.ImageField<never>;
}

/**
 * Default variation for FeaturedImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedImageSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FeaturedImageSliceDefaultPrimary>, never>;

/**
 * Slice variation for *FeaturedImage*
 */
type FeaturedImageSliceVariation = FeaturedImageSliceDefault;

/**
 * FeaturedImage Shared Slice
 *
 * - **API ID**: `featured_image`
 * - **Description**: FeaturedImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedImageSlice = prismic.SharedSlice<"featured_image", FeaturedImageSliceVariation>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
    /**
     * Quote field in *Quote → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: quote.default.primary.quote
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<"default", Simplify<QuoteSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *RichTextBlock → Default → Primary*
 */
export interface RichTextBlockSliceDefaultPrimary {
    /**
     * Rich Text Block field in *RichTextBlock → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text_block.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;
}

/**
 * Default variation for RichTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<RichTextBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *RichTextBlock*
 */
type RichTextBlockSliceVariation = RichTextBlockSliceDefault;

/**
 * RichTextBlock Shared Slice
 *
 * - **API ID**: `rich_text_block`
 * - **Description**: RichTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextBlockSlice = prismic.SharedSlice<"rich_text_block", RichTextBlockSliceVariation>;

declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }

    interface CreateWriteClient {
        (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
    }

    interface CreateMigration {
        (): prismic.Migration<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            BlogPostDocument,
            BlogPostDocumentData,
            BlogPostDocumentDataSlicesSlice,
            AllDocumentTypes,
            EmbeddedVideoSlice,
            EmbeddedVideoSliceDefaultPrimary,
            EmbeddedVideoSliceVariation,
            EmbeddedVideoSliceDefault,
            FeaturedImageSlice,
            FeaturedImageSliceDefaultPrimary,
            FeaturedImageSliceVariation,
            FeaturedImageSliceDefault,
            QuoteSlice,
            QuoteSliceDefaultPrimary,
            QuoteSliceVariation,
            QuoteSliceDefault,
            RichTextBlockSlice,
            RichTextBlockSliceDefaultPrimary,
            RichTextBlockSliceVariation,
            RichTextBlockSliceDefault,
        };
    }
}
