// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
    embedded_video: defineAsyncComponent(() => import("./EmbeddedVideo/index.vue")),
    featured_image: defineAsyncComponent(() => import("./FeaturedImage/index.vue")),
    quote: defineAsyncComponent(() => import("./Quote/index.vue")),
    rich_text_block: defineAsyncComponent(() => import("./RichTextBlock/index.vue")),
});
